### PR TITLE
Change return validity check

### PR DESCRIPTION
**Pull request by goetzk**
I was having trouble with this check as written (ansible 2.8) and required this change to progress.
Not sure how widely the issue might be so proposing here for discussion.

### CODE REVIEW

**Comment by goetzk** [comment]
Note for next time I come back to this: Its likely this is causing the centos failure due to reversed logic and should be 'when not true'.

**Comment by goetzk** [comment]
@mrlesmithjr I've taken a different approach to this change; hoping you can re-review it.

thanks,
Karl.

**Comment by mrlesmithjr** [comment]
@goetzk Can you rebase with master to get the latest updated CI tests?

**Comment by goetzk** [comment]
I see the failure on C7, i will follow it up tomorrow (that may be the reason things are as they are... sounding familiar now...)

**Comment by goetzk** [comment]
For reference: #15 added the systemd support.

**Pull request closed without merging**
